language: node_js
node_js:
  - "node"
install:
  - yarn
  - yarn flow-typed install
script:
  - yarn lint
  - yarn flow
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - yarn build && now build --public --name yard-frontend --token $NOW_TOKEN && now alias --token $NOW_TOKEN
