language: node_js
node_js:
  - "node"
install:
  - yarn
  - yarn flow-typed install
script:
  - yarn lint
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - yarn build && rm ./build/static/js/*.js.map && now build --public -e REACT_APP_MAPBOX_TOKEN=@yard-mapbox-token --name yard-frontend --token $NOW_TOKEN && now alias --token $NOW_TOKEN
