export default {
  fira: '"Fira Sans", "Helvetica", sans-serif',
  monaco: '"Monaco", "Consolas", "Lucida Console", monospace',
  philosopher: '"Philosopher", sans-serif',
  charcoalGrey: '#3e4247',
  slateGrey: '#646971',
  black: '#161616',
  blackTwo: '#000',
  blackThree: '#111',
  hueGrey: '#a9afb6',
  bgGrey: '#eaebf0',
  paleGrey: '#eaebf0',
  anotherGrey: '#e0e0e1',
  otherGrey: '#f4f5f9',
  coolBlue: '#00779a',
};
